version: '3.2'
services:
  product-service:
    build:
      context: product-service/
    ports:
      - 8088:8000
    container_name: product-service
  store-service:
    build:
      context: store-service/
    privileged: true
    user: root
    ports:
      - 8089:8000
    container_name: store-service